trigger:
    branches:
        include:
        - main

pool:
  vmImage: 'windows-2022'

variables:
  project: 'XBRLConverter/XBRLConverter/XBRLConverter.csproj'
  buildPlatform: 'Any CPU'

steps:
- task: UseDotNet@2
  displayName: Use .NET 
  inputs: 
    packageType: 'sdk'
    version: 6.x
    vsVersion: 17.0.x

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: build
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    projects: '$(project)'
    publishWebProjects: False
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
    includesymbols: False
    modifyOutputPath: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'xblr.converter.drop'